### ISSUE TITLE
Cyrillic letters problem

### ISSUE THREAD

**Issue by Proggggger** [scribeocr/scribeocr#56] opened 2024-08-06 11:48 UTC
When i trying to add additional languages recognition works normal, but final PDF document does not contain some letters like І Ї ї Є є,  can it be fixed in some way? (in DOCx format all letters are present)

**Comment by Balearica** [comment] 2024-08-06 18:06
The default fonts do not contain Cyrillic characters.  Separate fonts that do include Cyrillic characters do exist, and are loaded as needed.  The following line of code causes the extended fonts to be loaded when recognition is run with the Russian language.  To add additional languages that use Cyrillic characters, this line would need to be modified to add those language(s).  

https://github.com/scribeocr/scribeocr/blob/68164d76f5645bd0a9c5d7b3a27b8b8c9e801ad7/js/recognizeConvert.js#L413

**Comment by Proggggger** [comment] 2024-08-06 19:25
maybe, but the problem is not here
i tried to make such modifications, but still no result
the line you show is related to the recognition process, but recognition looks ok, i see all the characters on the web interface, but pdf generated does not contain them at all, just spaces, and characters can not be copied of course...

**Comment by Balearica** [comment] 2024-08-06 19:34
Please update the issue to include the language you are trying to add and a test document that produces the issues described.  We can't do anything further without a reproducible example.

> the line you show is related to the recognition process, but recognition looks ok, i see all the characters on the web interface, but pdf generated does not contain them at all, just spaces, and characters can not be copied of course...

This line is not specifically recognition-related, recognition is simply the trigger for fonts to be loaded.  When glyphs are not loaded, they often still appear in the browser interface because browsers have built-in fallback logic where the browser finds another font that does have the requested glyph.  This will not happen with the PDF output.

**Comment by Proggggger** [comment] 2024-08-06 19:51
[testforbugreport.pdf](https://github.com/user-attachments/files/16515029/testforbugreport.pdf)
Ok, not a problem, small test document with  needed glyphs, the language is Ukrainian

**Comment by Balearica** [comment] 2024-08-06 20:20
Thanks, I was able to replicate this issue using your example.  It looks like there are 3 letters (6 with capitalization) that are unique to the Ukrainian language (`ЄЇҐєїґ`), and for whatever reason, these were not included in our list of Cyrillic characters.  It should be quick for me to add these, I will do so now.

**Comment by Balearica** [comment] 2024-08-06 20:31
I updated the Cyrillic dictionary and added Ukrainian to the site in [this commit](https://github.com/scribeocr/scribeocr/commit/e17bf19a553e42ed7572248e163f58d94ca798c6).  It appears to work with the test document you provided.  Please confirm this resolves and we can close the issue.

**Comment by Proggggger** [comment] 2024-08-06 20:55
Thanks, i see that cyrillic capital і (І) also not present in the list for some reason

**Comment by Proggggger** [comment] 2024-08-06 21:09
And do you commit all changes? because for some reason i don't see changes. I pulled repo and checkout on e17bf19 but see the same output...

**Comment by Proggggger** [comment] 2024-08-06 21:38
Almost ok, (was also browser cache issue, when fonts was not updated, but now all except capital cyrillic І work.

**Comment by Balearica** [comment] 2024-08-07 00:28
I added the Cyrillic letter І.  Please let me know if everything works now.

**Comment by Proggggger** [comment] 2024-08-07 09:31
Thank you, looks like it works as it should, I think issue can be closed for now

**Comment by Balearica** [comment] 2024-08-18 06:16
Thanks for confirming, closing as completed.  

As a final check, I extracted all characters from the `unicharset` and `lstm-unicharset` files in `ukr.traineddata`, which are below, and confirmed all characters are in our current list of characters.  Therefore, we should be capable of representing any character the OCR model can detect when language is Ukrainian. 

```
!!""%''(())*+,,--..//00112233445566778899::;;=>??[]||©««»»ЄЄІІЇЇААББВВГГДДЕЕЖЖЗЗИИЙЙККЛЛММННООППРРССТТУУФФХХЦЦЧЧШШЩЩЬЬЮЮЯЯааббввггддеежжззииййккллммннооппррссттууффххццччшшщщыььэююяяєєііїїґ“”
```

**Closed by Balearica** 2024-08-18 06:16 UTC
