### ISSUE TITLE
text editing should be text-centric and keyboard-centric

### ISSUE THREAD

**Issue by milahu** [scribeocr/scribeocr#50] opened 2024-07-19 07:19 UTC
i want to use scribeocr to proofread and correct a bunch of hocr files from tesseract

currently i need to process a book of 200 pages...
so the current interface of scribeocr
(zoom, pan, click click type, click click type, pan, click click type, ...)
is rather painful to use, and makes this job at least 2x slower

expected:
the interface should be text-centric and keyboard-centric
just like a plain text editor

so i can use the arrow keys to seek...
characters (left, right)
lines (up, down)
words (ctrl+left, ctrl+right)
paragraphs (ctrl+up, ctrl+down)
pages (pageup, pagedown)

so i can use ctrl+shift+left, ctrl+shift+right to select words

so i can use ctrl+s to save the current hocr file to disk

or better:
convert hocr to plain text
let me proofread and correct the plain text file
then import the plain text file back to hocr

expected: be more like [hocr-proofreader](https://github.com/not-implemented/hocr-proofreader) ([demo](https://www.not-implemented.de/hocr-proofreader/))

**Comment by Balearica** [comment] 2024-07-19 18:10
> the interface should be text-centric and keyboard-centric

In general, I agree that adding more keyboard shortcuts would be a useful feature.

> convert hocr to plain text
let me proofread and correct the plain text file
then import the plain text file back to hocr
expected: be more like [hocr-proofreader](https://github.com/not-implemented/hocr-proofreader) ([demo](https://www.not-implemented.de/hocr-proofreader/))

Adding an entirely new proofreading interface would be outside of the scope of this project.  When used to proofread existing OCR data, the primary value-add of Scribe OCR is the visual editor that overlays the original document with the OCR data.  If this is a hinderance within your particular project versus a plain text editor, then I do not believe Scribe OCR is a good fit.

**Comment by milahu** [comment] 2024-07-19 18:48
out of scope, yes

currently im editing the hocr files with a text editor
and i have the pdf in a separate window, side by side
works ok so far

in the scribeocr ui, the bounding boxes are too irritating
i never change positions, i only want to fix some chars

so ideally, also the pointer actions (mouse, touch)
should go directly to the text (not after doubleclick)

maybe there can be 2 modes: edit text, edit positions

**Comment by Balearica** [comment] 2024-09-25 07:57
I added keyboard shortcuts that can be used to navigate between words and edit words, without taking your hands off the keyboard.  These are documented in the controls page of the docs [here](https://docs.scribeocr.com/controls.html#keyboard-shortcut-cheat-sheet).

Closing this issue, as I think the addition of shortcuts is the only actionable item in this issue.  As noted above, the data will always exist on the word-level, which precludes the UI from working like a text editor.

**Closed by Balearica** 2024-09-25 07:57 UTC
Labels: enhancement

**Comment by milahu** [comment] 2024-09-25 08:56
thanks : )

shortcuts for panning are missing

when i zoom into a page (fit page width to screen width)
then i must use the mouse wheel for vertical panning
(horizontal panning via shift+scroll is not implemented)

ideally the panning should be automatic
so the cursor is always visible

**Comment by Balearica** [comment] 2024-09-26 04:33
> (horizontal panning via shift+scroll is not implemented)

I added horizontal scrolling using `Shift + Scroll wheel`.

> ideally the panning should be automatic
so the cursor is always visible

This has been added; when you use shortcuts to select a word that is outside the current view, the screen will be panned to include it.

> also, i would expect ArrowRight to have the same effect as Tab:
at end of line, the cursor should jump to start of next line

This was initially how I implemented the feature, however it does not work well with complex layouts.  The issue is that what Tesseract decides is the "next line" is not predictable for certain document types.  For example, when working with data tables, the "next line" (`Tab`) shortcut may sometimes move the selection to the next column, and sometimes move the cursor to the next row.  This inconsistency is more frustrating than needing to work around a particular behavior.  Therefore, the arrow keys were implemented in a way that, while not ideal, is always completely predictable to the user.  If you click "right" the selection should always move to the visual right.

**Comment by milahu** [comment] 2024-09-26 06:40
more bugs / missing features ...

deleting whole words does not work
deleting some chars works
but it breaks as soon as i delete all chars of a word

"find text" should have shortcut Ctrl+F
repeating Ctrl+F = fallback to browser's text search

matching word stays highlighted after i close the text search

panning via `middleclick + mousemove` would be nice, like in inkscape

scrolling down should show the next page, like in a PDF viewer

after `next page` `ArrowUp` and `ArrowDown` are not working

after `next page` the cursor should be on the first word

the file basename of the current page should be visible somewhere

`Ctrl-Z` should undo, `Ctrl-Y` should redo (history)

`select files` should be limited to supported file types
hocr, png, jpg, ...

`select files` should be possible more than once
maybe add a file list, grouped by page

loading webp images does not work
"Import includes unsupported file types: webp"
limitation of `<canvas>`?
also: tiff, pnm, gif, ...
